site_description: 克瑞奇（Chritch）的笔记本 # 站点描述
site_name: 克瑞奇（Chritch）的笔记本 # 站点名字
copyright: Copyright &copy; 2022 - 2022 Zerokei
repo_url: https://github.com/Zerokei/Notes/

# choose a theme
theme:
  name: material
  palette:
  # 浅色模式
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo #主题色
    accent: red # 强调色
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  # 深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate 
    primary: blue # 主题色
    accent: red # 强调色
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features: 
    - navigation.tabs # 在上面一栏放置顶级目录
    - navigation.indexes # 为每个目录添加一个index
  font:
    text: JetBrains # 设置字体
    code: JetBrains Mono # 设置字体
  icon:
    logo: material/notebook-outline # 页面icon
  favicon: images/zerokei-logo.png # 标签icon
  language: 'zh' # 设置语言为中文

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition   # 提示块
  - pymdownx.details # 提示块可折叠
  - pymdownx.superfences # 代码嵌套在列表里
  - pymdownx.mark  # 文本高亮

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:yezk@zju.edu.cn
    - icon: fontawesome/brands/github
      link: https://github.com/Zerokei
    # - icon: fontawesome/solid/home
    #   link: https://zerokei.top
# 手动排版
nav:
  - Home:
    - index.md
  - Course:
    - course/index.md
    - Cryptography:
      - course/crypto/index.md
      - course/crypto/Math.md
      - course/crypto/old.md
      - course/crypto/md5.md
      - course/crypto/SHA1.md
      - course/crypto/rc4.md
      - course/crypto/DES.md
      - course/crypto/AES.md
      - course/crypto/RSA.md
      - course/crypto/ECC.md
      - course/crypto/final.md
    - Database System:
      - course/db/index.md
      - Relational Model & SQL:
        - course/db/sql/index.md
        - course/db/sql/algebra.md
        - course/db/sql/sql.md
      - course/db/ER.md
      - course/db/storage.md
      - Database Index:
        - course/db/index/index.md
        - course/db/index/Bplus.md
        - course/db/index/lsm.md
      - course/db/query.md
      - course/db/transaction.md
    - Advanced Data Structure and Algorithms:
      - course/ads/avl.md
      - course/ads/splay.md
      - course/ads/rb.md
      - course/ads/index.md
      - course/ads/back.md
      - course/ads/divide.md
      - course/ads/dp.md
      - course/ads/greedy.md
      - course/ads/np.md
      - course/ads/appr.md
      - course/ads/local.md
      - course/ads/random.md
      - course/ads/para.md
      - course/ads/external.md
  - Tutorials: 
    - tutorials/index.md
    - tutorials/mkdocs.md
    - tutorials/rsshub.md
  - Recommendation:
    - rec/index.md
  - Misc: 
    - misc/index.md
    - misc/schoolbus.md